configfile: "configs/config.yaml"


rule all:
    input:
        config['outrider']['results'],
        config['genes_gtf']


rule merge_gene_counts:
    input:
        count_dir = config['transcriptomics']['gene_count_dir'],
        samples = config['metadata']['participants']
    output:
        counts = config['output'] + '/counts/gene_counts.tsv'
    script:
        "scripts/merge_gene_counts.py"


rule filter_counts:
    input:
        gtf = config['gtf'],
        counts = rules.merge_gene_counts.output.counts
    output:
        ods = config['output'] + '/counts/ods_filtered.RDS',
        filtered_plot = config['output'] + '/counts/filtered.png'
    params:
        fpkm_cutoff = config['outrider']['fpkm_cutoff'],
        ensembl_release = config['genome']['ensembl_release']
    script:
        "scripts/filter_counts.R"


rule outrider:
    input:
        ods = rules.filter_counts.output.ods
    output:
        ods = config['output'] + '/outrider/ods.RDS',
        results = config['outrider']['results']
    params:
        padj_cutoff = config['outrider']['padj_cutoff']
    threads: 20
    script:
        "scripts/outrider.R"


rule outliers_genes:
    input:
        gtf = config['gtf'],
        results = config['outrider']['results']
    output:
        genes = config['genes_gtf']
    script:
        "scripts/genes_gtf.py"


rule compare_literature:
    input:
        nature_review = config['literature']['nature_review'],
        wgs = config['literature']['wgs'],
        genes = config['genes_gtf'],
        results = config['outrider']['results']
    output:
        fig_nature_review = 'reports/figures/literature_nature_review.png',
        fig_wgs = 'reports_figures/literature_wgs.png'
    notebook:
        "notebooks/compare_literature.ipynb"
