workdir: ".."


configfile: "scripts/config.yaml"


rule all:
    input:
        config['outrider']['results']


rule gene_counts:
    input:
        count_dir = config['transcriptomics']['gene_count_dir'],
        samples = config['metadata']['participants']
    output:
        counts = config['outrider']['counts']
    script:
        "merge_gene_counts.py"


rule outrider:
    input:
        counts = config['outrider']['counts']
    output:
        counts = config['outrider']['results']
    script:
        "outrider.R"
